# Flexlay - A Generic 2D Game Editor
# Copyright (C) 2002 Ingo Ruhnke <grumbel@gmx.de>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.

import os

env = Environment(SHLIBPREFIX="", ENV = os.environ)
env.ParseConfig("pkg-config --cflags --libs ruby-1.9")
env.ParseConfig("pkg-config --libs --cflags Qt5Gui Qt5Widgets")
env.Append(CXXFLAGS = ["-g", "-O2", "-Wall", "-fPIC"])

env.Append(CXXFLAGS = ["-std=c++11", "-Wno-uninitialized", "-Wno-unused-variable", "-Wno-unused-but-set-variable"],
           CPPPATH = [".", "../libflexlay/"],
           LIBPATH = ["../libflexlay/"],
           LIBS = ["flexlay"],
           SWIGFLAGS = ["-ruby", "-c++"],
           SHLIBPREFIX = "")

flexlay_ruby_lib = env.SharedLibrary(
    "flexlay_wrap",
    ["../libflexlay/flexlay_wrap.i",
     "ruby_functor.cpp",
     "ruby_meta_data.cpp",
     "ruby_sexpr_parser.cpp",
     "ruby_object.cpp",
     "ruby_converter.cpp"])

# EOF #

