## -*- mode: python -*-
##  $Id$
##
##  Flexlay - A Generic 2D Game Editor
##  Copyright (C) 2002 Ingo Ruhnke <grumbel@gmx.de>
##
##  This program is free software; you can redistribute it and/or
##  modify it under the terms of the GNU General Public License
##  as published by the Free Software Foundation; either version 2
##  of the License, or (at your option) any later version.
##
##  This program is distributed in the hope that it will be useful,
##  but WITHOUT ANY WARRANTY; without even the implied warranty of
##  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
##  GNU General Public License for more details.
##
##  You should have received a copy of the GNU General Public License
##  along with this program; if not, write to the Free Software
##  Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.

import os
import glob

opts = Options('custom.py')
opts.Add('CXX', 'The C++ compiler.', 'g++')
opts.Add('CXXFLAGS', 'The C++ compiler flags.', '-g -O2 -Wall')
opts.Add('CPPPATH', 'additional header path', '')
opts.Add('LIBPATH', 'additional library path', '')
opts.Add('RUBYDIR', 'Ruby directory', os.popen('ruby -e "require \'rbconfig\'; puts Config::CONFIG[\'archdir\']"').read()[:-1])

opts.Add('DESTDIR', 'destination directory which gets appended to PREFIX', '')
opts.Add('PREFIX',  'PREFIX, ie. /usr/local', '/usr/local')

env = Environment(SHLIBPREFIX='',
                  ENV = os.environ,
                  options=opts)
Help(opts.GenerateHelpText(env))

Depends('flexlay_wrap.i', ['clanlib.i'])
env.Command('flexlay_ruby_wrap.cxx',   'flexlay_wrap.i', "swig -ruby   -o flexlay_ruby_wrap.cxx -c++ $SOURCE")

#env.Program('sharedptrtest', 'sharedptrtest.cxx',
#            CPPPATH=['/home/ingo/run/ClanLib-0.7-current/include/ClanLib-0.7/'])

# env.Program('simpleed',
#             ['simpleed.cxx'],
#             CPPPATH=['.', 
#                     '/home/ingo/run/ClanLib-0.7-current//include/ClanLib-0.7/'],
#            LIBPATH=['.', '/home/ingo/run/ClanLib-0.7-current//lib/'],
#            LIBS=['flexlay'])

clanLib_env = Environment()
clanLib_env.ParseConfig("pkg-config --cflags --libs clanCore-0.7 clanDisplay-0.7 clanGL-0.7 clanSignals-0.7 clanGUI-0.7 clanGUIStyleSilver-0.7")

libflexlay_ruby_env = env.Copy()
flexlay_ruby_lib = libflexlay_ruby_env.SharedLibrary(
    target = 'flexlay_wrap.so',
    source = [
    'flexlay_ruby_wrap.cxx',
    'ruby_functor.cxx',
    'ruby_meta_data.cxx',
    'ruby_sexpr_parser.cxx',
    'ruby_object.cxx'
    ],
    CPPPATH=['$USER_CPPPATH','$RUBYDIR','..'] + clanLib_env['CPPPATH'],
    LINKFLAGS = clanLib_env['LINKFLAGS'],
    LIBPATH=['.'] + clanLib_env['LIBPATH'],
    LIBS=['flexlay'] + clanLib_env['LIBS'])

flexlay_data = \
             glob.glob('../data/images/files/*.png') + \
             glob.glob('../data/images/fonts/*.png') + \
             glob.glob('../data/images/icons16/*.png') + \
             glob.glob('../data/images/icons24/*.png') + \
             glob.glob('../data/images/netpanzersprites/*.png') + \
             glob.glob('../data/gui/gui.xml')    + \
             glob.glob('../data/gui/*/*.tga')    + \
             glob.glob('../data/gui/*/*.png')    + \
             glob.glob('../data/*.xml')

flexlay_headers = glob.glob('*.hxx')

flexlay_datadir = env['DESTDIR'] + env['PREFIX'] + '/share/flexlay'
# install_exec = env.Alias('install_exec', Install(env['DESTDIR'] + env['PREFIX'] + '/bin', flexlay_bin))
install_lib     = env.Alias('install_lib', Install(env['DESTDIR'] + env['PREFIX'] + '/lib', flexlay_lib))
install_headers = env.Alias('install_headers', Install(env['DESTDIR'] + env['PREFIX'] + '/include/flexlay', flexlay_headers))
install_data    = env.Alias('install_data', InstallAs([os.path.join(flexlay_datadir, i[8:]) for i in flexlay_data],
                                                      flexlay_data))
# install_ruby    = env.Alias('install_headers', Install(env['DESTDIR'] + env['PREFIX'] + '/include/flexlay', flexlay_headers))
env.Alias('install', [install_data, install_lib, install_headers])

# EOF #
