## -*- mode: python -*-
##  $Id$
##
##  Flexlay - A Generic 2D Game Editor
##  Copyright (C) 2002 Ingo Ruhnke <grumbel@gmx.de>
##
##  This program is free software; you can redistribute it and/or
##  modify it under the terms of the GNU General Public License
##  as published by the Free Software Foundation; either version 2
##  of the License, or (at your option) any later version.
##
##  This program is distributed in the hope that it will be useful,
##  but WITHOUT ANY WARRANTY; without even the implied warranty of
##  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
##  GNU General Public License for more details.
##
##  You should have received a copy of the GNU General Public License
##  along with this program; if not, write to the Free Software
##  Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.

import os
import glob

Import('clanLib_env')

opts = Variables('custom.py')
opts.Add('CXX', 'The C++ compiler.', 'g++')
opts.Add('CXXFLAGS', 'The C++ compiler flags.', '-g -O2 -Wall -fPIC -std=c++11')
opts.Add('CPPPATH', 'additional header path', '')
opts.Add('LIBPATH', 'additional library path', '')

opts.Add('DESTDIR', 'destination directory which gets appended to PREFIX', '')
opts.Add('PREFIX',  'PREFIX, ie. /usr/local', '/usr/local')

env = Environment(SHLIBPREFIX='',
                  ENV = os.environ,
                  options=opts)
Help(opts.GenerateHelpText(env))

Depends('netpanzer.i', ['netpanzer.hpp'])
env.Command('netpanzer_wrap.cpp', 'netpanzer.i',
            "swig -c++ -ruby -o $TARGET $SOURCE")

env.ParseConfig("pkg-config --cflags --libs ruby-2.2")
libflexlay_ruby_env = env.Clone()
flexlay_ruby_lib = libflexlay_ruby_env.SharedLibrary(
    target = 'netpanzer_wrap.so',
    source = [
    'netpanzer_wrap.cpp',
    'netpanzer.cpp'
    ],
    CPPPATH=['$USER_CPPPATH', '../lib/'] + clanLib_env['CPPPATH'] + env['CPPPATH'],
    LINKFLAGS = clanLib_env['LINKFLAGS'],
    LIBPATH=['../lib', '../ruby'] + clanLib_env['LIBPATH'],
    LIBS=['flexlay'] + clanLib_env['LIBS'])

# install_ruby = env.Alias('install_headers', Install(env['DESTDIR'] + env['PREFIX'] + '/include/flexlay', flexlay_headers))
# env.Alias('install', [install_ruby])

# EOF #
