# Flexlay - A Generic 2D Game Editor
# Copyright (C) 2004 Ingo Ruhnke <grumbel@gmx.de>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.

import os

env = Environment(ENV = os.environ)
env.ParseConfig("pkg-config --cflags --libs Qt5Gui")
env.ParseConfig("pkg-config --cflags --libs ruby-1.9")
env.Append(
    CPPPATH = ["../libflexlay/"],
    CXXFLAGS = ["-g", "-O2", "-Wall", "-Wunused-but-set-variable", "-fPIC", "-std=c++11"],
    LIBPATH = ["../libflexlay", "../ruby"],
    LIBS = ["flexlay"],
    SWIGFLAGS = ["-ruby", "-c++"])
env.Replace(SHLIBPREFIX = "")

flexlay_ruby_lib = env.SharedLibrary(
    "netpanzer_wrap",
    ["netpanzer.i",
     "netpanzer.cpp"])

# EOF #
