#!/usr/bin/env python3

import os, webbrowser, datetime

if __name__ == "__main__":
    input("DO NOT USE THIS PROGRAM! IT IS TEMPORARY AND FOR KARKUS476'S DEVELOPMENT PURPOSES ONLY. Ctrl+C NOW!!!")
    cwd = os.getcwd()
    print("Current working directory is:", cwd)
    print("Generating documentation...")
    os.system("doxygen")
    print("Done!")
    print("Opening web browser...")
    webbrowser.open("http://karkus476.github.io/flexapi-docs")
    print("Done!")
    print("Pushing to Karkus476's repo")
    os.chdir("..")
    os.system("git add -A;"\
            "git commit -m \"Updated docs on " + datetime.datetime.now().strftime("%Y-%m-%d %H:%M")+"\";" \
            "git push origin origin/gh-pages;")
