env = Environment()
env.ParseConfig('sdl-config --cflags --libs')
env['CXXFLAGS'] += ['-O0', '-Wall', '-g']
env['LIBS'] += ['Xi']
env.Program('wacom', ['wacom.cpp',
                      'input_device_xinput.cpp'])

# EOF #


