# -*- python -*-

# Set to False to use local ClanLib instead of global one
if True:
    clanLib_env = Environment(LIBPATH=[])
    clanLib_env.ParseConfig("pkg-config --cflags --libs " +
                            "clanCore-0.8 clanDisplay-0.8 clanGL-0.8 clanSignals-0.8 clanGUI-0.8 clanGUIStyleSilver-0.8")
else:
    # FIXME: replace the X11 stuff with a proper X11 configure check and
    # make them somehow part of the clanlib libraries themself
    clanLib_env = Environment(CPPPATH=['../external/clanlib/'],
                              LIBPATH=['/usr/X11R6/lib/',
                                       '../external/clanlib/'],
                              LIBS=['clanGUIStyleSilver', 
                                    'clanGUI',      
                                    'clanGL',
                                    'clanDisplay',
                                    'clanSignals', 
                                    'clanCore',
                                    'X11', 'Xmu', 'GL', 'GLU', 'png', 'jpeg', 'Xxf86vm', 'Xi'])

Export('clanLib_env')

SConscript(['external/clanlib/SConstruct'])
SConscript(['lib/SConscript'])
SConscript(['ruby/SConscript'])
SConscript(['supertux/SConstruct'])
SConscript(['netpanzer/SConscript'])

# EOF #
