##  Flexlay - A Generic 2D Game Editor
##  Copyright (C) 2004 Ingo Ruhnke <grumbel@gmx.de>
##
##  This program is free software; you can redistribute it and/or
##  modify it under the terms of the GNU General Public License
##  as published by the Free Software Foundation; either version 2
##  of the License, or (at your option) any later version.
##
##  This program is distributed in the hope that it will be useful,
##  but WITHOUT ANY WARRANTY; without even the implied warranty of
##  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
##  GNU General Public License for more details.
##
##  You should have received a copy of the GNU General Public License
##  along with this program; if not, write to the Free Software
##  Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.

import os

env = Environment(ENV = os.environ)
env.ParseConfig("pkg-config --libs --cflags Qt5Gui Qt5Widgets Qt5OpenGL")
env.ParseConfig("pkg-config --libs --cflags gl")
env.ParseConfig("pkg-config --cflags --libs " +
                "clanCore-1.0 clanDisplay-1.0 clanGL-1.0 clanSignals-1.0 clanGUI-1.0 clanGUIStyleSilver-1.0")
env.Append(CPPPATH = ["."])
env.Append(CXXFLAGS = ['-g3', '-O0', '-Wall', '-std=c++11'])

flexlay_lib = env.SharedLibrary('flexlay', Glob('*.cpp') + Glob('*/*.cpp'))

# EOF #
