#! /bin/sh

echo "Generating netpanzertiles.py"
echo "# Automatically generated by 'mknetpanzertiles.sh'" > netpanzertiles.py
echo "from flexlay import *" >> netpanzertiles.py
echo "def load_netpanzer_tiles(tileset):" >> netpanzertiles.py
for i in images/netpanzertiles/*.png; 
do
#  BASENAME=`basename $i`
  BASENAME=${i##images/netpanzertiles/tile}
  BASENAME=${BASENAME%%.png}
  BASENAME=${BASENAME##0}
  BASENAME=${BASENAME##0}
  BASENAME=${BASENAME##0}
  echo "   tileset.add_tile(${BASENAME},"
  echo "                    Tile(\"../data/$i\","
  echo "                         CL_Color(254, 254, 254, 254),"
  echo "                         CL_Color(255,   0,   0, 128)))"
done >> netpanzertiles.py
echo "" >> netpanzertiles.py
echo "# EOF #" >> netpanzertiles.py

# EOF #
